### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Vincent-L-P** [psohn/Posture-Check#1]
Hi there, 

I cloned this repo but unable to run this. Would you mind share some detailed instruction about how to run this package? Thanks!

**Comment by psohn** [comment]
Hi Vincent, could you give more details on what isn't working?

**Comment by Vincent-L-P** [comment]
Hi Philip, usually I clone the package from github and then run the setup.py. As your package doesn't come with this file, I am not sure how to install and use this package. Would you mind provide some details about install and run this package? Also, does this package rely on any other library I need to install? Thanks!

**Comment by psohn** [comment]
Apologies, I've never actually had someone fork one of my repos before. I'll make it easier to use and give an update within a week.

**Comment by psohn** [comment]
It should work now. Thanks for informing me of this problem!
